### ISSUE TITLE
v2.03 pages include “last updated”, whereas it’s removed from all older versions

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Standard-SSOT#143] opened 2018-02-27 16:04 UTC
There were a bunch of PRs (e.g. #115) to earlier version branches, to remove “last updated” footnote from all pages. A similar PR hasn’t been applied to v2.03, so it’s still there:

https://github.com/IATI/IATI-Standard-SSOT/blob/666472c8df14d4b5bb85b57437b71626782d1334/combined_gen.sh#L24

**Comment by andylolz** [comment] 2018-03-01 17:41
Worth pointing out: It _loooooks_ like this feature is all working correctly for v2.03. I suspect the issues described in #115 are a result of the deployment process. That is: perhaps the git repository in `/docs` on the build server was broken in some way?

**Comment by samuele-mattiuzzo** [comment] 2019-01-15 16:36
Closing, as the issue is actually the opposite (would be nice to show last_updated, we're not showing it instead).

**Closed as completed by samuele-mattiuzzo** 2019-01-15 16:36 UTC

**Comment by andylolz** [comment] 2019-01-15 16:42
Looks to be missing from v2.03 documentation now anyway.
