### ISSUE TITLE
Lots of whitespace has appeared on codelist pages

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Standard-SSOT#344] opened 2019-08-28 14:44 UTC
E.g. http://reference.iatistandard.org/203/codelists/Version/

Looks like this:
![Screenshot 2019-08-28 at 15 42 23](https://user-images.githubusercontent.com/464193/63866004-766d2b00-c9aa-11e9-8a1c-f77ac4b8cd4c.png)

**Comment by andylolz** [comment] 2019-08-28 14:55
Guessing here, but I wonder if this relates to the recent major upgrade of Sphinx? (from 1.2.3 to 2.1.2) in #136.

**Comment by samuele-mattiuzzo** [comment] 2019-08-28 15:00
I don't see a problem with it tbh, I had noticed it and to be fair the whitespace increases the readability of these pages.

**Comment by andylolz** [comment] 2019-08-28 15:39
Relatedly, this stuff has been added to the bottom of the sidebar:

![Screenshot 2019-08-28 at 16 38 23](https://user-images.githubusercontent.com/464193/63870651-46c22100-c9b2-11e9-9c93-ae73899be862.png)

Again, it seems probable that this relates to the Sphinx upgrade.

**Comment by samuele-mattiuzzo** [comment] 2019-09-02 15:23
Deployed and sorted on our live instances, thanks again @andylolz 👍 

I'll close this now, feel free to re-open it and comment further if the issue is still... an issue

**Closed as completed by samuele-mattiuzzo** 2019-09-02 15:23 UTC
