### ISSUE TITLE
Codelist API link and IATI Codelist Management appear twice in the navigation

### ISSUE THREAD

**Issue by samuele-mattiuzzo** [IATI/IATI-Standard-SSOT#201] opened 2018-10-11 14:06 UTC
In this page http://iatistandard.org/202/codelists/, `IATI Codelist Management` and `Codelist API` are linked twice and it makes sense as they are first grouped as `General Information` then as `All Codelists`

In the nav on the left handside, however, they are not grouped as such, so they appear twice (at the start and at the end of the list).

Worth fixing if the effort isn't massive

**Comment by andylolz** [comment] 2018-10-11 17:43
Duplicate of https://github.com/IATI/IATI-Extra-Documentation/issues/198 (although probably makes more sense on this repo).

**Closed as completed** 2018-11-09 13:33 UTC
Labels: bug
